### ISSUE TITLE
Feature: Infinite

### ISSUE THREAD

**Issue by jdconner** [express-labs/pure-react-carousel#167] opened 2019-08-29 13:56 UTC
Hi there.

Love the implementation and declarative style of this library. The only thing keeping my company and I from using this lib is that its missing the `infinite` option (see https://react-slick.neostack.com/). The feature is essentially: `if we're currently on the last slide and the user hits the next button, go to the first set of slides. if we're on the first set of slides and the user hits the back button, go to the last set of slides`. All around, it is a better user experience than completely disabling the next/back buttons.

Example:

![Aug-29-2019 08-55-13](https://user-images.githubusercontent.com/12697946/63946422-bed42980-ca3a-11e9-86cd-b49a04a02686.gif)

I've started to implement the feature as you can see above, and it seems like it'll take minimum effort to add the feature. Looking for your thoughts on adding this feature before I go any further to support edge cases  (e.g. where the total number of slides is not divisible by the visible slides) and add tests.

EDIT:

This is an optional prop. Without passing the prop, you get the original functionality.

**Comment by fabb** [comment] 2019-09-04 09:56
This is a duplicate of #60

**Closed** 2019-09-27 04:31 UTC
Labels: wontfix

**Comment by alcoelho** [comment] 2019-10-01 22:02
How is it going? This feature is really important

**Comment by jdconner** [comment] 2019-10-02 13:28
@alcoelho I was told this was already being worked on: https://github.com/express-labs/pure-react-carousel/issues/60 so I stopped. I am considering just finishing it up and submitting a PR, or just forking the repo at this point.

**Comment by tim-steele** [comment] 2019-10-02 13:54
@jdconner if you have a solution, we would welcome a PR.

We have something we have been working on here at Express, but it is unfinished and unpolished. If you have something that works, then we would welcome a PR and to collaborate on it.

**Comment by jdconner** [comment] 2019-10-03 16:37
@tim-steele I'll see if I can find time to finish it up; just as most of us here, I also have a day job. Do you guys have a branch of the unfinished work? It could help me identify what you're expecting ahead of time and also reduce some of the work I'll need to do.

**Comment by tim-steele** [comment] 2019-10-03 17:56
@jdconner absolutely, we will get the branch pushed up.

**Comment by tim-steele** [comment] 2019-10-06 15:28
@jdconner I am reviewing the PR now.

**Comment by tim-steele** [comment] 2019-10-06 20:00
@jdconner I published out version 1.23.0 which has your code merged in.

**Comment by Aca1995** [comment] 2021-04-01 09:15
Hello guys, small question about this. :) 

If we're currently on the last slide and we hit next button, is it possible to go to the first slide without slider going all back to it, but to slide to it normally, so that the first slide appear immediately after the last slide?

**Comment by rishabh2712** [comment] 2021-09-24 04:50
Currently, the slider, after the last slide, goes through all the slides till the first to start again. 

What is desired is after the last slide, slider goes to first slide as if its the next slide seamlessly. How to achieve this?

**Comment by NairiAreg** [comment] 2022-04-29 09:50
> Currently, the slider, after the last slide, goes through all the slides till the first to start again.
> 
> What is desired is after the last slide, slider goes to first slide as if its the next slide seamlessly. How to achieve this?

Any news in that? Or should I code it manually :/

**Comment by Hagafny** [comment] 2022-07-24 14:11
I agree. After the last slide, we'd like to just naturally go to the first slide. How could this be done?
