### ISSUE TITLE
TranslateX wrong settings

### ISSUE THREAD

**Issue by coljung** [express-labs/pure-react-carousel#329] opened 2021-01-11 14:30 UTC
So I have a very simple Carousel:

<CarouselProvider
            naturalSlideWidth={400}
            naturalSlideHeight={400}
            totalSlides={5}>
            <Slider><Slide index={0}><img src={process.env.PUBLIC_URL + '/img/01.jpg'} alt="" /></Slide>
              <Slide index={1}><img src={process.env.PUBLIC_URL + '/img/02.jpg'} alt="" /></Slide>
              <Slide index={2}><img src={process.env.PUBLIC_URL + '/img/03.jpg'} alt="" /></Slide>
              <Slide index={3}><img src={process.env.PUBLIC_URL + '/img/04.jpg'} alt="" /></Slide>
              <Slide index={4}><img src={process.env.PUBLIC_URL + '/img/05.jpg'} alt="" /></Slide>
              
            </Slider>
          </CarouselProvider>
Images are capped to 400px and drag with the mouse works fine.

But i noticed that depending on how strong I move the mouse, the container parent <ul class="sliderTray...> gets 2 translateX properties added. The first one makes complete sense, as it manages the % all images are moved left-right. But the second translateX is messing up the carousel. So my i end up with something like:

transform: translateX(-20%) translateX(-257px)

All your demos seem to snap properly, mine for some reason doesnt, but not sure what im missing here.

**Comment by tim-steele** [comment] 2021-01-11 18:21
Duplicate of #324.

**Closed by tim-steele** 2021-01-11 18:21 UTC
